In [158]:
import numpy as np
import pandas as pd

class Node:
    def __init__(self, n_weights: int) -> None:
        # Identity of an object, i.e., a Node
        self.node_id = str(id(self))[7:]
        
        # Create random weights that match the number of inputs
        # TODO optimize later
        # 1 bias per node and n weights for each corresponding input per node
        self.weights = np.random.uniform(low=-1.0, high=1.0, size=n_weights) 
        self.bias = 0 # np.random.uniform(low=0.0, high=10.0, size=None)
        
    def __str__(self) -> str:
        return f"Node {self.node_id}|{len(self.weights)}"
    
    def out(self, input_):
        return np.dot(self.weights,input_) + self.bias


class NeuralNetwork():
    def __init__(self, n_inputs, hidden_layers_struct, n_outputs) -> None:
        self.inputs = n_inputs
        self.outputs = n_outputs
        
        self.network_structure = [n_inputs] + hidden_layers_struct

        self.node_weights = [] # ?
        self.node_bias = [] # ?
        
        self.hidden_layers = self.__construct_hidden_layers__()
    
    def show_structure(self) -> str:
        print("Info: ", len(self.hidden_layers), " hidden layers")
        
        for indx, layer in enumerate(self.hidden_layers):
            print(f"Hidden layer {indx + 1} has {len(layer)} nodes: \n", 
                  np.array(
                      [f"Node {n.node_id}|{len(n.weights)} weights" for n in layer]
                  ).reshape(-1,1), '\n')
    
    def __construct_hidden_layers__(self):
        weights = [i for i in self.network_structure]
        matrix = []
        
        for layer in self.network_structure[1:len(self.network_structure)]:
            n_weights = weights.pop(0)
            
            self.node_weights.append([Node(n_weights).weights for n in range(layer)]) # ?
            self.node_bias.append([Node(n_weights).bias for n in range(layer)])# ?
            
            layer_nodes = [Node(n_weights) for n in range(layer)]
            matrix.append(layer_nodes)
        return np.array(matrix, dtype=object)
    
    def forward_propagate(self, input_, layer=0, verbose = False):
        if layer == len(self.hidden_layers):
            return input_
        else:
            layer_output = []
            
            for node in self.hidden_layers[layer]:
                layer_output.append(node.out(input_))
            
            # for layer_weights in self.node_weights:# ?
            #     layer_output = np.dot(layer_weights, input_) + self.node_bias# ?
                    
            if verbose:
                print(f"Layer {layer} input: \n", input_)
                print(f"Layer {layer} output: \n", layer_output, "\n")
                
            return self.forward_propagate(layer_output, layer+1)
            

In [159]:
nn = NeuralNetwork(n_inputs = 4, hidden_layers_struct = [3], n_outputs = 3)

test = [[ 0.2 , 0.8 , - 0.5 , 1 ],
[ 0.5 , - 0.91 , 0.26 , - 0.5 ],
[ - 0.26 , - 0.27 , 0.17 , 0.87 ]]

bias = [2,3,0.5]

anticipated_result = [ 4.8 , 1.21 , 2.385 ]

for i, new in zip(nn.hidden_layers[0], test):
    i.weights = new
    print("Assigned test weigts", i.weights)

for i, new in zip(nn.hidden_layers[0], bias):
    i.bias = new
    print("Asseigned test bieas", i.bias)

assert nn.forward_propagate(np.array([ 1 , 2 , 3 , 2.5 ])) == anticipated_result
print("Success!")

Assigned test weigts [0.2, 0.8, -0.5, 1]
Assigned test weigts [0.5, -0.91, 0.26, -0.5]
Assigned test weigts [-0.26, -0.27, 0.17, 0.87]
Asseigned test bieas 2
Asseigned test bieas 3
Asseigned test bieas 0.5
Success!


In [161]:
import numpy as np
import pandas as pd

class Node:
    def __init__(self, n_weights: int) -> None:
        # Identity of an object, i.e., a Node
        self.node_id = str(id(self))[7:]
        
        # Create random weights that match the number of inputs
        # TODO optimize later
        # 1 bias per node and n weights for each corresponding input per node
        self.weights = np.random.uniform(low=-1.0, high=1.0, size=n_weights) 
        self.bias = 0 # np.random.uniform(low=0.0, high=10.0, size=None)
        
    def __str__(self) -> str:
        return f"Node {self.node_id}|{len(self.weights)}"
    
    def out(self, input_):
        return np.dot(self.weights,input_) + self.bias


class NeuralNetwork():
    def __init__(self, n_inputs, hidden_layers_struct, n_outputs) -> None:
        self.inputs = n_inputs
        self.outputs = n_outputs
        
        self.network_structure = [n_inputs] + hidden_layers_struct

        self.node_weights = [] # ?
        self.node_bias = [] # ?
        
        self.hidden_layers = self.__construct_hidden_layers__()
    
    def show_structure(self) -> str:
        print("Info: ", len(self.hidden_layers), " hidden layers")
        
        for indx, layer in enumerate(self.hidden_layers):
            print(f"Hidden layer {indx + 1} has {len(layer)} nodes: \n", 
                  np.array(
                      [f"Node {n.node_id}|{len(n.weights)} weights" for n in layer]
                  ).reshape(-1,1), '\n')
    
    def __construct_hidden_layers__(self):
        weights = [i for i in self.network_structure]
        matrix = []
        
        for layer in self.network_structure[1:len(self.network_structure)]:
            n_weights = weights.pop(0)
            
            self.node_weights.append([Node(n_weights).weights for n in range(layer)]) # ?
            self.node_bias.append([Node(n_weights).bias for n in range(layer)])# ?
            
            layer_nodes = [Node(n_weights) for n in range(layer)]
            matrix.append(layer_nodes)
        return np.array(matrix, dtype=object)
    
    def apply_custom_weights_bias(self, w, b):
        for layer in self.hidden_layers:
            for i, new in zip(layer, w):
                i.weights = new
                print("Assigned test weigts", i.weights)

            for i, new in zip(layer, b):
                i.bias = new
                print("Asseigned test bieas", i.bias)
        
        self.node_weights = []
        self.node_bias = []
        for layer in self.network_structure[1:len(self.network_structure)]:
            n_weights = len(weights.pop(0))

            self.node_weights.append([Node(n_weights).weights for n in range(layer)]) # ?
            self.node_bias.append([Node(n_weights).bias for n in range(layer)])# ?
    
    def forward_propagate(self, input_, layer=0, verbose = False):
        if layer == len(self.hidden_layers):
            return input_
        else:
            layer_output = []
            
            for layer_order in range(len(self.hidden_layers)):# ?
                layer_output = np.dot(input_, np.array(self.node_weights[layer_order]).T) + self.node_bias[layer_order]# ?
                
            if verbose:
                print(f"Layer {layer} input: \n", input_)
                print(f"Layer {layer} output: \n", layer_output, "\n")
                
            return self.forward_propagate(layer_output, layer+1)
            

In [162]:
inputs = [[ 1.0 , 2.0 , 3.0 , 2.5 ],
[ 2.0 , 5.0 , - 1.0 , 2.0 ],
[ - 1.5 , 2.7 , 3.3 , - 0.8 ]]

weights = [[ 0.2 , 0.8 , - 0.5 , 1.0 ],
[ 0.5 , - 0.91 , 0.26 , - 0.5 ],
[ - 0.26 , - 0.27 , 0.17 , 0.87 ]]
biases = [ 2.0 , 3.0 , 0.5 ]

layer_outputs = np.dot(inputs, np.array(weights).T) + biases

nn = NeuralNetwork(n_inputs = 4, hidden_layers_struct = [3], n_outputs = 3)
nn.apply_custom_weights_bias(weights, biases)

print(layer_outputs)
print(nn.forward_propagate(inputs))

# assert nn.forward_propagate(inputs) == layer_outputs
pirnt("Success!")

Assigned test weigts [0.2, 0.8, -0.5, 1.0]
Assigned test weigts [0.5, -0.91, 0.26, -0.5]
Assigned test weigts [-0.26, -0.27, 0.17, 0.87]
Asseigned test bieas 2.0
Asseigned test bieas 3.0
Asseigned test bieas 0.5
[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
[[ 0.5409062   1.58618502 -0.76466009]
 [ 1.4157819  -2.54269725 -4.12310179]
 [ 0.63964311 -0.11288271 -0.86892763]]


NameError: name 'pirnt' is not defined